LEARNING THE NUMPY LIBRARY -->IT IS AN LINEAR ALGEBRA LIBRARY FOR PYTHON IT IS FAST AND HAS BINDINGS TO THE C LIBRARY

In [46]:
import numpy as np

In [47]:
my=[1,2,3]

In [48]:
my

[1, 2, 3]

In [49]:
arr=np.array(my)

In [50]:
arr

array([1, 2, 3])

In [51]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
pr=np.arange(0,25)

In [53]:
pr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
pr.shape

(25,)

In [55]:
a=pr.reshape(5,5)

In [56]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
a.shape

(5, 5)

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

GETTING RANDOM INTEGER FROM 0 TO 1

In [59]:
np.random.rand(5)

array([0.93281338, 0.56279318, 0.70785229, 0.27306659, 0.2008385 ])

In [60]:
np.random.randn(2)

array([1.05671016, 1.17815951])

In [61]:
np.random.randint(10,20)

10

In [62]:
ra=np.random.randint(1,100,20)

In [63]:
ra

array([49, 16, 31, 96, 21, 38, 24, 17, 80, 34, 52, 37, 42, 54, 29, 97, 14,
       48, 24, 72])

In [64]:
ra.max()

97

In [65]:
ra.min()

14

FINDING THE INDEX OF MAX ELEMENT IN THE ARRAY

In [66]:
ra.argmax()

15

FINDING THE INDEX OF MIN ELEMENT IN THE ARRAY

In [67]:
ra.argmin()

16

Numpy array indexing and selection

In [68]:
import numpy as np


In [69]:
arr=np.arange(0,11)

In [70]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr[8]

8

In [72]:
arr[1:5]

array([1, 2, 3, 4])

In [73]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [74]:
arr[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
arr[-4:]

array([ 7,  8,  9, 10])

In [76]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
arr[:5]

array([0, 1, 2, 3, 4])

In [78]:
arr[0:5]=100

In [79]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [80]:
arr=np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This will not create an copy of array basically slice_arr is an new array refrenced to arr array 
so if i change th slic_arr then the arr array will also be changed so keep that in min

In [82]:
slice_arr=arr[0:6]

In [83]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [84]:
slice_arr[:]=99

In [85]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [86]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

So basically the below code is for array copy so we are creating an copy of the array arr not refrencing it so it is independent of arr , basically if we change arr_copy the arr array will not be changed
fo r this we will use arr.copy() method

In [87]:
arr_copy=arr.copy()

In [88]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [89]:
arr_copy[:]=100

In [90]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [91]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

2d arrays numpy

In [92]:
import numpy as np

In [93]:
arr_2d=np.array([[5,10,15],[20,25,23],[35,40,45]])

In [94]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 23],
       [35, 40, 45]])

Double bracket notation

In [95]:
arr_2d[0][0]

5

In [96]:
arr_2d[0]

array([ 5, 10, 15])

using the single bracket notaion

In [97]:
arr_2d[1,2]

23

In [98]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 23]])

In [99]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 23]])

In [100]:
arr_2d[1:]

array([[20, 25, 23],
       [35, 40, 45]])

In [101]:
arr_2d[1:,1:]

array([[25, 23],
       [40, 45]])

IMPORTANT ->SELECTION conditional selections


In [102]:
arr=np.arange(1,11)

In [103]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
bool_arr=arr>5

In [106]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [108]:
bool_a=arr[arr>5]

In [109]:
bool_a

array([ 6,  7,  8,  9, 10])

In [111]:
arr_2d=np.arange(50).reshape(5,10)

In [112]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [115]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [118]:
arr_2d[2:4,7:9]

array([[27, 28],
       [37, 38]])

NUMPY BASIC OPERATIONS


->ARRAY WITH ARRAY
->ARRAY WITH SCALERS
->UNIVERSAL ARRAY FUNCTIONS


In [1]:
import numpy as np


In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

-->array with scalar operations

In [6]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [7]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [8]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

------DIVIDE BY ZERO IS AN ERROR BUT NUMPY DOESNOT DISPLAY AN ERROR IT DISPLAYS A WARNING------

In [9]:
1/0

ZeroDivisionError: division by zero

In [10]:
arr/arr

C:\Users\RoG STRIX\AppData\Local\Temp\ipykernel_13356\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
1/arr

C:\Users\RoG STRIX\AppData\Local\Temp\ipykernel_13356\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408])

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.max(arr)

10

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [20]:
np.log(arr)

C:\Users\RoG STRIX\AppData\Local\Temp\ipykernel_13356\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

-->exercise for me

In [21]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [23]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.rand()

0.7676303373870536

In [30]:
np.random.randint(26)

2

In [29]:
np.random.randn(25)

array([-2.03653573,  0.38259098, -1.54840823, -1.03536142,  0.18904611,
        0.35768156,  0.71489696,  0.35834136,  0.30341338,  0.39775994,
        0.12150801,  1.30401002,  0.45707983, -2.25047289,  1.26757491,
        1.36187299, -1.65431009, -0.76962677, -0.3386498 ,  0.04384531,
        0.3392593 ,  0.9135865 ,  0.55254721, -1.02685579, -0.04022107])

In [31]:
np.arange(0,1,0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [32]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])